/**
 * Canonical site URL + SEO defaults for Sacred Reference (2026).
 */

/** Always the public production origin (no trailing slash). */
export const PRODUCTION_SITE_URL = "https://www.oursacredreference.com";

/**
 * Public site origin for metadata, sitemap, robots, and JSON-LD.
 * Never returns localhost — local/preview envs fall back to production
 * so crawl surfaces (especially sitemap.xml) stay valid for GSC.
 */
export function getSiteUrl(): string {
  const fromEnv = process.env.NEXT_PUBLIC_SITE_URL?.trim().replace(/\/$/, "");
  if (
    fromEnv &&
    !/localhost|127\.0\.0\.1|0\.0\.0\.0|movetrusthub/i.test(fromEnv) &&
    /^https:\/\//i.test(fromEnv)
  ) {
    // Prefer the canonical production host when env points at a Vercel preview
    if (
      /oursacredreference\.com$/i.test(fromEnv.replace(/^https?:\/\//, "")) ||
      fromEnv === PRODUCTION_SITE_URL
    ) {
      // Normalize apex → www
      if (fromEnv === "https://oursacredreference.com") {
        return PRODUCTION_SITE_URL;
      }
      return fromEnv;
    }
    // Preview / other hosts: still use production for SEO public URLs
    return PRODUCTION_SITE_URL;
  }
  return PRODUCTION_SITE_URL;
}

export const SEO = {
  siteName: "Sacred Reference",
  defaultTitle: "Sacred Reference | Mytho-Shamanic Somatic Healing",
  titleTemplate: "%s | Sacred Reference",
  /** Primary meta description — authentic mission + niche keywords */
  defaultDescription:
    "Beneath every wound, every defense, and every life story there is Wholeness, something sacred waiting to be remembered. Mytho-shamanic somatic healing, felt sense, Divine Feminine, and a Path of Remembering with Michele Castro.",
  locale: "en_US",
  twitterHandle: undefined as string | undefined,
  practitioner: "Michele Castro",
  email: "michele@oursacredreference.com",
  /** Shared OG path — generated by app/opengraph-image.tsx */
  ogImagePath: "/opengraph-image",
  keywords: [
    "mytho-shamanic somatic healing",
    "somatic coaching online",
    "felt sense therapy alternative",
    "Path of Remembering",
    "Divine Feminine embodiment",
    "Divine Mother spirituality",
    "Dark Goddess work",
    "Jungian depth psychology coaching",
    "embodied spirituality",
    "feminine wisdom healing",
    "nervous system regulation coaching",
    "inner child integration somatic",
    "Michele Castro",
    "Sacred Reference",
    "online discovery session somatic",
    "myth as lived experience",
    "soul-language symptoms",
  ],
} as const;

export type PageSeoInput = {
  title: string;
  description: string;
  path: string;
  keywords?: string[];
  type?: "website" | "article";
  noIndex?: boolean;
  publishedTime?: string;
  authors?: string[];
  images?: string[];
};

export function buildPageMetadata(input: PageSeoInput) {
  const site = getSiteUrl();
  const url = `${site}${input.path === "/" ? "" : input.path}`;
  const images = input.images?.length
    ? input.images
    : [`${site}${SEO.ogImagePath}`];

  return {
    title: input.title,
    description: input.description,
    keywords: input.keywords ?? [...SEO.keywords],
    authors: (input.authors ?? [SEO.practitioner]).map((name) => ({ name })),
    alternates: {
      canonical: url,
    },
    openGraph: {
      title: input.title.includes("Sacred Reference")
        ? input.title
        : `${input.title} | ${SEO.siteName}`,
      description: input.description,
      url,
      siteName: SEO.siteName,
      locale: SEO.locale,
      type: input.type ?? "website",
      images: images.map((img) => ({
        url: img,
        width: 1200,
        height: 630,
        alt: input.title,
      })),
      ...(input.publishedTime
        ? { publishedTime: input.publishedTime }
        : {}),
    },
    twitter: {
      card: "summary_large_image" as const,
      title: input.title,
      description: input.description,
      images,
    },
    robots: input.noIndex
      ? {
          index: false,
          follow: false,
          googleBot: { index: false, follow: false },
        }
      : {
          index: true,
          follow: true,
          googleBot: {
            index: true,
            follow: true,
            "max-image-preview": "large" as const,
            "max-snippet": -1,
            "max-video-preview": -1,
          },
        },
  };
}
